### ISSUE TITLE
Highlighting in CI browse with Chrome & Firefox

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#37] opened 2015-12-13 13:59 UTC
@davidwtalley & @abievans, there is a difference in visual behavior in browsing the comp index at [1] on Chrome and Firefox. When you expand the browse index in Firefox, you get an annoying highlighting of all nodes of a taxon path (see image below) but you do not get that affect with Chrome (see image below). Chrome is by the far the better visual outcome.

FIREFOX:
![firefox-browse](https://cloud.githubusercontent.com/assets/2939046/11767305/28daf390-a15e-11e5-86e9-573a9d933e33.png)

CHROME:
![chrome-browse](https://cloud.githubusercontent.com/assets/2939046/11767308/47940e2a-a15e-11e5-8157-6d156ed9da4c.png)

[1] http://explore.dublincore.net/linked-data-learning-resources/

**Comment by davidwtalley** [comment] 2015-12-13 21:30
I reproduced this on FF, Win7.

I found a CSS fix for this [1 - thanks goodness for Stackoverflow!!] and added it to the theme options custom CSS tab. Seems to resolve the issue on FF with no effect on Chrome. I think both of you are on Macs, @stuartasutton & @abievans -- can you validate the fix there? And Abi, please let me know if that looks like it might have undesirable effects elsewhere.

[1]

**Comment by stuartasutton** [comment] 2015-12-13 23:19
Correct, I am on a Mac. The fix seemed to have solved the problem. I'll wait to close the issue until we hear from Abi.

**Comment by abievans** [comment] 2015-12-14 14:58
The fix looks good to me. I don’t see any issues related to the custom CSS.

**Closed** 2015-12-31 13:16 UTC
Labels: bug
